# Template for Kubernetes secrets
# DO NOT commit actual secrets to git!
# Use DigitalOcean Secrets or External Secrets Operator

# Create secrets with:
# kubectl create secret generic konqer-secrets -n saas \
#   --from-literal=database-url="postgresql://..." \
#   --from-literal=stripe-secret="sk_..." \
#   --from-literal=stripe-webhook-secret="whsec_..." \
#   --from-literal=stripe-founding-price-id="price_..." \
#   --from-literal=openai-key="sk-..." \
#   --from-literal=apollo-key="..." \
#   --from-literal=keycloak-client-secret="..." \
#   --from-literal=jwt-public-key="-----BEGIN PUBLIC KEY-----..."

apiVersion: v1
kind: Secret
metadata:
  name: konqer-secrets
  namespace: saas
type: Opaque
stringData:
  database-url: "postgresql://konqer:PASSWORD@postgres-central.platform.svc.cluster.local:5432/konqer_production"
  stripe-secret: "REPLACE_WITH_STRIPE_SECRET_KEY"
  stripe-webhook-secret: "REPLACE_WITH_STRIPE_WEBHOOK_SECRET"
  stripe-founding-price-id: "REPLACE_WITH_STRIPE_PRICE_ID"
  openai-key: "REPLACE_WITH_OPENAI_API_KEY"
  apollo-key: "REPLACE_WITH_APOLLO_API_KEY"
  keycloak-client-secret: "REPLACE_WITH_KEYCLOAK_CLIENT_SECRET"
  jwt-public-key: "REPLACE_WITH_KEYCLOAK_PUBLIC_KEY"
