name: Deploy Frontend Sites

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'apps/cold-dm/**'
      - 'apps/objection/**'
      - 'apps/carousel/**'
      - 'packages/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'apps/web') || github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build konqer-app
      run: pnpm --filter=konqer-app build

    - name: Deploy to Kinsta
      env:
        KINSTA_GITHUB_TOKEN: ${{ secrets.KINSTA_GITHUB_TOKEN }}
      run: |
        cd apps/web/out
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy ${{ github.sha }}"
        git push --force https://x-access-token:${KINSTA_GITHUB_TOKEN}@github.com/Digiclevr/konqer-web.git main

  deploy-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [cold-dm, objection, carousel]
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-node: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build ${{ matrix.service }}
      run: pnpm --filter=${{ matrix.service }} build

    - name: Deploy ${{ matrix.service }} to Kinsta
      env:
        KINSTA_GITHUB_TOKEN: ${{ secrets.KINSTA_GITHUB_TOKEN }}
      run: |
        cd apps/${{ matrix.service }}/out
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy ${{ github.sha }}"
        git push --force https://x-access-token:${KINSTA_GITHUB_TOKEN}@github.com/Digiclevr/konqer-${{ matrix.service }}.git main
