name: Deploy API Backend

on:
  push:
    branches: [main]
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DigitalOcean Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRY_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      run: |
        docker build \
          -t registry.digitalocean.com/konqer/api:${{ github.sha }} \
          -t registry.digitalocean.com/konqer/api:latest \
          -f apps/api/Dockerfile \
          apps/api

        docker push registry.digitalocean.com/konqer/api:${{ github.sha }}
        docker push registry.digitalocean.com/konqer/api:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure kubectl
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_BASE64 }}
      run: |
        echo "$KUBECONFIG_DATA" | base64 -d > kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl config current-context

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ./kubeconfig
      run: |
        kubectl set image deployment/konqer-api \
          api=registry.digitalocean.com/konqer/api:${{ github.sha }} \
          -n saas

        kubectl rollout status deployment/konqer-api -n saas --timeout=5m

    - name: Verify deployment
      env:
        KUBECONFIG: ./kubeconfig
      run: |
        kubectl get pods -n saas -l app=konqer-api
        kubectl get svc -n saas konqer-api-svc

    - name: Notify on success
      if: success()
      run: |
        echo "✅ API deployed successfully"
        echo "Image: registry.digitalocean.com/konqer/api:${{ github.sha }}"

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ API deployment failed"
        kubectl logs -n saas -l app=konqer-api --tail=50
